name: Hello world!
description: 👋 Greet someone and record the time

inputs:
  name:
    description: Who to greet
    default: ${{ github.actor }}

outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: _main.mjs
