inputs:
  github-action-path:
    description: github.action_path
    required: true
  inputs:
    description: toJSON(inputs)
    required: true
  main:
    description: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsmain
    required: true
  pre-if:
    description: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre-if
    default: true
  pre:
    description: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspre
  post-if:
    description: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost-if
    default: true
  post:
    description: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost

runs:
  using: node20
  main: src/main.js
  pre-if: inputs.pre && inputs.pre-if
  pre: src/pre.js
  post-if: inputs.post && inputs.post-if
  post: src/post.js
