name: Draft Release
on:
  workflow_dispatch:
jobs:
  draft-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git checkout -b temp-$RANDOM
      - run: rm .gitignore
      - run: npm install
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: git add -Av && git commit -m 'Draft release'
      - run: git push -u origin $(git branch --show-current)
      - run: gh release create ' ' -d --target $(git rev-parse HEAD~1)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: always()
        run: git push -d origin $(git branch --show-current)
