name: Test all
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-all.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-all.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-deno:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm install -g serve
      - run: nohup npx serve -p 5000 & sleep 5
      - uses: ./test/hello-world
  test-separate-file:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm install -g serve
      - run: nohup npx serve -p 5000 & sleep 5
      - uses: ./test/separate-file
