name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - id: main
        uses: ./
        with:
          inputs: '{"message":"Hello world!"}'
          env: ${{ toJSON(env) }}
          main: main.ts
        env:
          GITHUB_ACTION_PATH: ${{ github.workspace }}/test
      - shell: bash
        run: echo "$OUTPUTS" | jq
        env:
          OUTPUTS: ${{ toJSON(steps.main.outputs) }}
