name: Test action
on:
  push:
    branches: "main"
  pull_request:
jobs:
  test-action:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: deno compile -o main main.ts
      - id: main
        uses: ./
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
