name: Update Deno
on:
  workflow_dispatch:
    inputs:
      deno-version:
        description: Semver specifier
        type: string
        required: true
jobs:
  update-deno:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - id: setup-deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ inputs.deno-version }}
      - shell: bash
        run: |
          echo "$TARGETS" | while read target; do
            export DENO_INSTALL=".deno/$target"
            curl -fsSL "https://github.com/denoland/deno/releases/download/v$DENO_VERSION/deno-$target.zip" -o "/tmp/deno-$target.zip"
            rm -rf "$DENO_INSTALL"
            unzip -d "$DENO_INSTALL" "/tmp/deno-$target.zip"
            gzip "$DENO_INSTALL/bin/deno"
          done
        env:
          DENO_VERSION: ${{ steps.setup-deno.outputs.deno-version }}
          TARGETS: |
            x86_64-pc-windows-msvc
            x86_64-apple-darwin
            aarch64-apple-darwin
            x86_64-unknown-linux-gnu
      - uses: stefanzweifel/git-auto-commit-action@v5
